---
grails:
    config:
        locations:
            - ~/.grails/gokb-config.groovy
            - ~/.grails/gokb-config.yml
            - ~/.grails/gokb-config.properties
    cors:
        enabled: true
        mappings:
            /rest/**: inherit

    profile: web
    codegen:
        defaultPackage: gokbg3
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    mime:
        file:
            extensions: false
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 50000000
            maxRequestSize: 50000000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    exceptionresolver:
        params:
            exclude:
                - password
                - password2
                - email
    plugin:
        springsecurity:
            rest:
                token:
                    validation:
                        endpointUrl: /rest/validate
                login:
                    endpointUrl: /rest/login
                logout:
                    endpointUrl: /rest/logout
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.grails.version@'

spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://pghost:5432/gokbg3dev
            username: knowint
            password: knowint
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
        grails:
            logging:
                plugin:
                    springsecurity:
                        debug:
                            useFilter: true
            mail:
                port: 3025
        gokb:
            ygorUrl: null
            packageUpdate:
                enabled: false
            es:
                cluster: gokbg3-dev
                host: localhost
                indices:
                    titles: gokbtitles
                    tipps: gokbtipps
                    orgs: gokborgs
                    packages: gokbpackages
                    platforms: gokbplatforms
            tsvExportTempDirectory: /tmp/gokb/export
        cache:
            headers:
                enabled: false
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:postgresql://pghost:5432/gokbg3test
            username: knowint
            password: knowint
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
        gokb:
            ygorUrl: null
            packageUpdate:
                enabled: false
            es:
                cluster: gokbg3-test
                host: localhost
                indices:
                    titles: gokbtitles
                    tipps: gokbtipps
                    orgs: gokborgs
                    packages: gokbpackages
                    platforms: gokbplatforms
        grails:
            mail:
                port: 3025
        quartz:
            pluginEnabled: false
        cache:
            headers:
                enabled: false
        javamelody:
            disabled: true
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/gokbg3
            username: gokb
            password: knowint
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
            pooled: true
            properties:
                maxActive: 100
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                validationQuery: select 1
                defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
        grails:
            plugin:
                greenmail:
                    disabled: true
        gokb:
            packageUpdate:
                enabled: false
            ygorUrl: null
            es:
                cluster: gokbg3-prod
                host: localhost
                indices:
                    titles: gokbtitles
                    tipps: gokbtipps
                    orgs: gokborgs
                    packages: gokbpackages
                    platforms: gokbplatforms
gokb:
    defaultCuratoryGroup: Local
    ftupdate_enabled: true
    decisionSupport:
        active: false
        otherVoters: false
    costInfo: false

quartz:
    autoStartup: true
    waitForJobsToCompleteOnShutdown: false
